client_config_backend: file
client_config:
    client_id: 152640747953-sgomtn2acq3sefk4d1759rifbju3q54t.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive